Markdown note test

In [4]:
d = {'key1':'value','key2':123}
d['key1']

'value'

In [6]:
d = {'k1':[1,2,3]}
my_list = d['k1']
my_list[0]

1

In [7]:
d = {'k1':{'k2':[1,2,3]}}
d['k1']['k2']


[1, 2, 3]

In [8]:
1 == 1

True

In [9]:
1 == 2

False

In [10]:
1 != 1

False

In [11]:
seq = [1,2,3,4,5]
for item in seq:
    print(item)

1
2
3
4
5


In [12]:
i = 1
while i<5:
    print('i is equal to {}'.format(i))
    i += 1

i is equal to 1
i is equal to 2
i is equal to 3
i is equal to 4


In [13]:
for x in range(0,5):
    print(x)

0
1
2
3
4


In [14]:
x = [1,2,3,4]
out = []
for num in x:
    out.append(num**2)
print(out)

[1, 4, 9, 16]


In [15]:
[num**2 for num in x]

[1, 4, 9, 16]

In [16]:
def my_func(param1):
    print(param1)

In [18]:
my_func('hello')

hello


In [19]:
"""
THIS IS A MULTILINE STRING

USING THREE SETS OF QUOTATIONS

"""

'\nTHIS IS A MULTILINE STRING\n\nUSING THREE SETS OF QUOTATIONS\n\n'

In [21]:
def times2(var):
    return var*2
seq = [1,2,3,4,5]
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [22]:
t = lambda var:var*2
list(map(t,seq))

[2, 4, 6, 8, 10]

In [23]:
list(filter(lambda num: num%2 == 0, seq))

[2, 4]

In [24]:
s = 'hello my name is Trevor'
s.lower()

'hello my name is trevor'

In [25]:
s.upper()

'HELLO MY NAME IS TREVOR'

In [26]:
s.split()

['hello', 'my', 'name', 'is', 'Trevor']

In [27]:
tweet = 'Go Sports! #Sports'
tweet.split('#')[1]

'Sports'

In [28]:
x = [(1,2),(3,4),(5,6)]
for (a,b) in x:
    print(a)
    print(b)

1
2
3
4
5
6


In [1]:
s = 'Is there a cat in this sentence?'
'cat' in s.lower().split()

True

In [3]:
my_list = [1,2,3]
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(my_mat)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [7]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [12]:
np.linspace(1,10,10)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [13]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [14]:
np.linspace(0,5,100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [15]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
arr = np.arange(25)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr = np.random.randint(0,50,10)

In [19]:
ranarr

array([35, 40, 16, 28, 29, 43, 20, 27, 48,  7])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
ranarr.max()

48

In [22]:
ranarr.min()

7

In [23]:
ranarr.argmax()

8

In [24]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [25]:
arr.dtype

dtype('int32')

In [26]:
arr = np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[8]

8

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [34]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[2,0]

35

In [38]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [39]:
arr = np.arange(1,11)
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [40]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [41]:
arr[arr<3]

array([1, 2])

In [42]:
arr_2d = np.arange(50).reshape(5,10)

In [43]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [6]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [7]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [1]:
import numpy as np
import pandas as pd
labels = ['a','b','c']       #list
my_data = [10,20,30]         #list
arr = np.array(my_data)     #numpy array
d = {'a':10,'b':20,'c':30}   #dictionary

In [2]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [3]:
pd.Series(data = my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [9]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan',])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [10]:
ser2 = pd.Series([1,2,5,4],['USA','Germany','Italy','Japan',])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [11]:
ser1['USA']

1

In [12]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [13]:
from numpy.random import randn

In [15]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  1.558322 -0.578205 -0.964762 -0.743570
B  0.720290  1.944477 -0.456675  0.405224
C -1.305469  0.734961  0.359607 -0.959572
D -0.455347  1.301812 -1.488179  0.722969
E  0.231665 -2.344375 -0.906513 -0.087369

In [16]:
df['W']

A    1.558322
B    0.720290
C   -1.305469
D   -0.455347
E    0.231665
Name: W, dtype: float64

In [19]:
df['new'] = df['W'] + df['Y']
df

W         X         Y         Z       new
A  1.558322 -0.578205 -0.964762 -0.743570  0.593560
B  0.720290  1.944477 -0.456675  0.405224  0.263615
C -1.305469  0.734961  0.359607 -0.959572 -0.945862
D -0.455347  1.301812 -1.488179  0.722969 -1.943525
E  0.231665 -2.344375 -0.906513 -0.087369 -0.674848

In [21]:
df.drop('new',axis=1)

W         X         Y         Z
A  1.558322 -0.578205 -0.964762 -0.743570
B  0.720290  1.944477 -0.456675  0.405224
C -1.305469  0.734961  0.359607 -0.959572
D -0.455347  1.301812 -1.488179  0.722969
E  0.231665 -2.344375 -0.906513 -0.087369

In [24]:
df.drop('new',axis=1,inplace=True)

In [25]:
df.drop('E',axis=0)

W         X         Y         Z
A  1.558322 -0.578205 -0.964762 -0.743570
B  0.720290  1.944477 -0.456675  0.405224
C -1.305469  0.734961  0.359607 -0.959572
D -0.455347  1.301812 -1.488179  0.722969

In [26]:
df.shape

(5, 4)

In [27]:
df.loc['A']

W    1.558322
X   -0.578205
Y   -0.964762
Z   -0.743570
Name: A, dtype: float64

In [29]:
df.iloc[0]

W    1.558322
X   -0.578205
Y   -0.964762
Z   -0.743570
Name: A, dtype: float64

In [30]:
df.loc['B','Y']

-0.45667467781584092

In [31]:
df.loc[['A','B'],['W','Y']]

W         Y
A  1.558322 -0.964762
B  0.720290 -0.456675

In [33]:
booldf  = df > 0

In [34]:
df[booldf]

W         X         Y         Z
A  1.558322       NaN       NaN       NaN
B  0.720290  1.944477       NaN  0.405224
C       NaN  0.734961  0.359607       NaN
D       NaN  1.301812       NaN  0.722969
E  0.231665       NaN       NaN       NaN

In [36]:
df[df['Z']<0]

W         X         Y         Z
A  1.558322 -0.578205 -0.964762 -0.743570
C -1.305469  0.734961  0.359607 -0.959572
E  0.231665 -2.344375 -0.906513 -0.087369

In [37]:
df[(df['W']>0) & (df['Y']>1)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [38]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [39]:
df['States'] = newind

In [40]:
df

W         X         Y         Z States
A  1.558322 -0.578205 -0.964762 -0.743570     CA
B  0.720290  1.944477 -0.456675  0.405224     NY
C -1.305469  0.734961  0.359607 -0.959572     WY
D -0.455347  1.301812 -1.488179  0.722969     OR
E  0.231665 -2.344375 -0.906513 -0.087369     CO

In [41]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      1.558322 -0.578205 -0.964762 -0.743570
NY      0.720290  1.944477 -0.456675  0.405224
WY     -1.305469  0.734961  0.359607 -0.959572
OR     -0.455347  1.301812 -1.488179  0.722969
CO      0.231665 -2.344375 -0.906513 -0.087369

In [42]:
outside = 'G1 G1 G1 G2 G2 G2'.split()
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [46]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [51]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [52]:
df

A         B
G1 1  0.320426 -0.090839
   2 -1.093436 -1.738622
   3 -1.649995 -0.122779
G2 1  1.013697  0.052849
   2 -2.035659 -1.101345
   3 -0.674755  1.133361

In [54]:
df.loc['G1'].loc[1]

A    0.320426
B   -0.090839
Name: 1, dtype: float64

In [56]:
df.loc['G2'].loc[2,'B']

-1.1013454447261162

In [59]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
df = pd.DataFrame(d)

In [60]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [62]:
df.dropna(axis=1,thresh=2)

A  C
0  1.0  1
1  2.0  2
2  NaN  3

In [63]:
df.fillna(value='Fuck you')

A         B  C
0         1         5  1
1         2  Fuck you  2
2  Fuck you  Fuck you  3

In [65]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [3]:
import numpy as np
import pandas as pd
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],'Sales':[200,120,340,124,243,350]}
df = pd.DateFrame(data)

AttributeError: module 'pandas' has no attribute 'DatFrame'